/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vezerles;

import javax.swing.JFrame;

/**
 *
 * @author Szintai
 */
public class InditoFrame extends javax.swing.JFrame {

    private String cim = "Kvíz Játék";
    private int szelesseg = 1118;
    private int magassag = 636;
    private Vezerlo vezerlo;

    /**
     * Creates new form vezerloFrame
     */
    public InditoFrame() {
        initComponents();
        beallitasok();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temakorPanel1 = new feluletek.BeallitasPanel();
        bejelentkezoPanel1 = new feluletek.BejelentkezoPanel();
        jatekTerPanel1 = new feluletek.JatekTerPanel();
        menuPanel1 = new feluletek.MenuPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(temakorPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(bejelentkezoPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jatekTerPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(menuPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InditoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InditoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InditoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InditoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InditoFrame().start();
            }
        });
    }

    private void start() {
        this.setVisible(true);
        vezerlo = new Vezerlo(jatekTerPanel1, bejelentkezoPanel1, menuPanel1, temakorPanel1);
        vezerlo.statikusbeallitas();
        menuPanel1.setVezerlo(vezerlo);
        bejelentkezoPanel1.setVezerlo(vezerlo);
        jatekTerPanel1.setVezerlo(vezerlo);
        temakorPanel1.setVezerlo(vezerlo);
    }

    private void beallitasok() {
        this.setSize(szelesseg, magassag);
        this.setLocationRelativeTo(null);
        this.setTitle(cim);
        bejelentkezoPanel1.setVisible(false);
        menuPanel1.setVisible(true);
        temakorPanel1.setVisible(false);
        jatekTerPanel1.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private feluletek.BejelentkezoPanel bejelentkezoPanel1;
    private feluletek.JatekTerPanel jatekTerPanel1;
    private feluletek.MenuPanel menuPanel1;
    private feluletek.BeallitasPanel temakorPanel1;
    // End of variables declaration//GEN-END:variables
}
