/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import vezerles.Vezerlo;
import vezerles.Vezerlo.TemakorEnum;

/**
 *
 * @author Szintai
 */
public class BeallitasPanel extends javax.swing.JPanel {

    /**
     * Creates new form TemakorPanel
     */
    private Vezerlo vezerlo;
    List<JCheckBox> checkBoxok = new ArrayList<JCheckBox>();
    private Image hatterKep = new ImageIcon(getClass().getResource("/adatok/hatter2.jpg")).getImage();
    ResourceBundle magyarBundle = ResourceBundle.getBundle("lokalitas/Bundle");
    ResourceBundle angolBundle = ResourceBundle.getBundle("lokalitas/Bundle_en");
    private String nincsNev = "Adjon meg egy nevet";
    private Icon hangBe = new ImageIcon(getClass().getResource("/adatok/hangBe.png"));
    private Icon hangKi = new ImageIcon(getClass().getResource("/adatok/hangKi.png"));
    private List<TemakorEnum> temakorok = new ArrayList<>();
    int szamlalo = 0;
    boolean osszesKerdesE = false;
    private boolean osszesKerdesAktivalas;

    public BeallitasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        chkTvSorozat = new javax.swing.JCheckBox();
        chkFoldrajzi = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkElovilag = new javax.swing.JCheckBox();
        chkSzolasokEsKozmondasok = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkKozlekedesEsJarmuvek = new javax.swing.JCheckBox();
        chkBulvar = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkZene = new javax.swing.JCheckBox();
        chkUnnepek = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkFilmEsSzinhaz = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        chkKepzomuveszeti = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        chkEtelekEsItalok = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        chkOsszesKijeloles = new javax.swing.JCheckBox();
        chkIrodalmi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chkOsszesKijelolesTorles = new javax.swing.JCheckBox();
        chkEgyeb = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkCsillagaszat = new javax.swing.JCheckBox();
        chkTortenelmi = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnAngol = new javax.swing.JButton();
        btnZene = new javax.swing.JButton();
        btnMagyar = new javax.swing.JButton();

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Földrajzi");

        chkTvSorozat.setBackground(new java.awt.Color(255, 255, 255));
        chkTvSorozat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkTvSorozat.setForeground(new java.awt.Color(255, 255, 255));
        chkTvSorozat.setSelected(true);

        chkFoldrajzi.setBackground(new java.awt.Color(255, 255, 255));
        chkFoldrajzi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkFoldrajzi.setForeground(new java.awt.Color(255, 255, 255));
        chkFoldrajzi.setSelected(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Szólások és közmondások");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Élővilág");

        chkElovilag.setBackground(new java.awt.Color(255, 255, 255));
        chkElovilag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkElovilag.setForeground(new java.awt.Color(255, 255, 255));
        chkElovilag.setSelected(true);

        chkSzolasokEsKozmondasok.setBackground(new java.awt.Color(255, 255, 255));
        chkSzolasokEsKozmondasok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkSzolasokEsKozmondasok.setForeground(new java.awt.Color(255, 255, 255));
        chkSzolasokEsKozmondasok.setSelected(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Egyéb");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Zene");

        chkKozlekedesEsJarmuvek.setBackground(new java.awt.Color(255, 255, 255));
        chkKozlekedesEsJarmuvek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkKozlekedesEsJarmuvek.setForeground(new java.awt.Color(255, 255, 255));
        chkKozlekedesEsJarmuvek.setSelected(true);

        chkBulvar.setBackground(new java.awt.Color(255, 255, 255));
        chkBulvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkBulvar.setForeground(new java.awt.Color(255, 255, 255));
        chkBulvar.setSelected(true);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Közlekedés és járművek");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bulvár");

        chkZene.setBackground(new java.awt.Color(255, 255, 255));
        chkZene.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkZene.setForeground(new java.awt.Color(255, 255, 255));
        chkZene.setSelected(true);

        chkUnnepek.setBackground(new java.awt.Color(255, 255, 255));
        chkUnnepek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkUnnepek.setForeground(new java.awt.Color(255, 255, 255));
        chkUnnepek.setSelected(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Film és színház");

        chkFilmEsSzinhaz.setBackground(new java.awt.Color(255, 255, 255));
        chkFilmEsSzinhaz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkFilmEsSzinhaz.setForeground(new java.awt.Color(255, 255, 255));
        chkFilmEsSzinhaz.setSelected(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Képzőművészet");

        chkKepzomuveszeti.setBackground(new java.awt.Color(255, 255, 255));
        chkKepzomuveszeti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkKepzomuveszeti.setForeground(new java.awt.Color(255, 255, 255));
        chkKepzomuveszeti.setSelected(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ételek és italok");

        chkEtelekEsItalok.setBackground(new java.awt.Color(255, 255, 255));
        chkEtelekEsItalok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkEtelekEsItalok.setForeground(new java.awt.Color(255, 255, 255));
        chkEtelekEsItalok.setSelected(true);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ünnepek");

        chkOsszesKijeloles.setBackground(new java.awt.Color(255, 255, 255));
        chkOsszesKijeloles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkOsszesKijeloles.setForeground(new java.awt.Color(255, 255, 255));
        chkOsszesKijeloles.setSelected(true);
        chkOsszesKijeloles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOsszesKijelolesActionPerformed(evt);
            }
        });

        chkIrodalmi.setBackground(new java.awt.Color(255, 255, 255));
        chkIrodalmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkIrodalmi.setForeground(new java.awt.Color(255, 255, 255));
        chkIrodalmi.setSelected(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Összes kijelölés:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Irodalom");

        chkOsszesKijelolesTorles.setBackground(new java.awt.Color(255, 255, 255));
        chkOsszesKijelolesTorles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkOsszesKijelolesTorles.setForeground(new java.awt.Color(255, 255, 255));
        chkOsszesKijelolesTorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOsszesKijelolesTorlesActionPerformed(evt);
            }
        });

        chkEgyeb.setBackground(new java.awt.Color(255, 255, 255));
        chkEgyeb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkEgyeb.setForeground(new java.awt.Color(255, 255, 255));
        chkEgyeb.setSelected(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Összes törlés:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Csillagászat");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Történelmi");

        chkCsillagaszat.setBackground(new java.awt.Color(255, 255, 255));
        chkCsillagaszat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCsillagaszat.setForeground(new java.awt.Color(255, 255, 255));
        chkCsillagaszat.setSelected(true);

        chkTortenelmi.setBackground(new java.awt.Color(255, 255, 255));
        chkTortenelmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkTortenelmi.setForeground(new java.awt.Color(255, 255, 255));
        chkTortenelmi.setSelected(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tv sorozat");

        btnMenu.setBackground(java.awt.SystemColor.activeCaption);
        btnMenu.setText("Menü");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnAngol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/eng.png"))); // NOI18N
        btnAngol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngolActionPerformed(evt);
            }
        });

        btnZene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/hangBe.png"))); // NOI18N
        btnZene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeneActionPerformed(evt);
            }
        });

        btnMagyar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/hun.png"))); // NOI18N
        btnMagyar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagyarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkOsszesKijeloles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(chkOsszesKijelolesTorles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTortenelmi)
                            .addComponent(chkFoldrajzi)
                            .addComponent(chkBulvar)
                            .addComponent(chkElovilag)
                            .addComponent(chkZene))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkFilmEsSzinhaz)
                                            .addComponent(chkKepzomuveszeti)
                                            .addComponent(chkIrodalmi))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(41, 41, 41)
                                        .addComponent(chkUnnepek)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(42, 42, 42)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSzolasokEsKozmondasok)
                                    .addComponent(chkEgyeb)
                                    .addComponent(chkKozlekedesEsJarmuvek)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkCsillagaszat)
                                            .addComponent(chkTvSorozat))
                                        .addGap(155, 155, 155)
                                        .addComponent(btnMagyar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnZene, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAngol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(chkEtelekEsItalok)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(chkCsillagaszat)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMagyar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAngol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(chkTvSorozat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(chkKozlekedesEsJarmuvek)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkOsszesKijeloles)
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(chkOsszesKijelolesTorles))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(chkUnnepek))
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(chkTortenelmi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chkFoldrajzi)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chkBulvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(chkFilmEsSzinhaz))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(chkKepzomuveszeti))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(chkIrodalmi))))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel5)
                                            .addComponent(chkElovilag)
                                            .addComponent(chkEtelekEsItalok)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkZene)
                                                    .addComponent(jLabel6)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel16))))
                                    .addComponent(chkSzolasokEsKozmondasok)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(chkEgyeb)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkOsszesKijelolesTorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOsszesKijelolesTorlesActionPerformed

        if (chkOsszesKijelolesTorles.isSelected()) {
            osszesKerdesAktivalas = false;
            chkBoxokKipipalvaCsere();
            chkOsszesKijeloles.setSelected(osszesKerdesAktivalas);
        }

    }//GEN-LAST:event_chkOsszesKijelolesTorlesActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        g.drawImage(hatterKep, 0, 0, this.getWidth(), this.getHeight(), this);

    }

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        vezerlo.panelCsere(false, false, false, true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAngolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngolActionPerformed
        vezerlo.nyelvvaltas(angolBundle);
        vezerlo.temakorMenuElerhetosegCsere(false);
        btnMagyar.setEnabled(true);
        btnAngol.setEnabled(false);
        vezerlo.bundleMenuPanel(true, false);
    }//GEN-LAST:event_btnAngolActionPerformed

    private void btnZeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeneActionPerformed
        if (!btnZene.getIcon().equals(hangKi)) {
            vezerlo.zeneBeKapcsolas();
            btnZene.setIcon(hangKi);
            vezerlo.menuPanelHangBEKI(false);
        } else {
            vezerlo.zeneKikapcsolas();
            vezerlo.menuPanelHangBEKI(true);
            btnZene.setIcon(hangBe);
        }


    }//GEN-LAST:event_btnZeneActionPerformed

    private void btnMagyarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagyarActionPerformed
        vezerlo.nyelvvaltas(magyarBundle);
        vezerlo.temakorMenuElerhetosegCsere(true);
        btnMagyar.setEnabled(false);
        btnAngol.setEnabled(true);
        vezerlo.bundleMenuPanel(false, true);
    }//GEN-LAST:event_btnMagyarActionPerformed

    private void chkOsszesKijelolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOsszesKijelolesActionPerformed
        if (chkOsszesKijeloles.isSelected()) {
            osszesKerdesAktivalas = true;
            chkBoxokKipipalvaCsere();
            chkOsszesKijelolesTorles.setSelected(!osszesKerdesAktivalas);
        }
    }//GEN-LAST:event_chkOsszesKijelolesActionPerformed

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAngol;
    private javax.swing.JButton btnMagyar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnZene;
    private javax.swing.JCheckBox chkBulvar;
    private javax.swing.JCheckBox chkCsillagaszat;
    private javax.swing.JCheckBox chkEgyeb;
    private javax.swing.JCheckBox chkElovilag;
    private javax.swing.JCheckBox chkEtelekEsItalok;
    private javax.swing.JCheckBox chkFilmEsSzinhaz;
    private javax.swing.JCheckBox chkFoldrajzi;
    private javax.swing.JCheckBox chkIrodalmi;
    private javax.swing.JCheckBox chkKepzomuveszeti;
    private javax.swing.JCheckBox chkKozlekedesEsJarmuvek;
    private javax.swing.JCheckBox chkOsszesKijeloles;
    private javax.swing.JCheckBox chkOsszesKijelolesTorles;
    private javax.swing.JCheckBox chkSzolasokEsKozmondasok;
    private javax.swing.JCheckBox chkTortenelmi;
    private javax.swing.JCheckBox chkTvSorozat;
    private javax.swing.JCheckBox chkUnnepek;
    private javax.swing.JCheckBox chkZene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public List<TemakorEnum> kerdesTemakorLekeres() {
        szamlalo = 0;
        temakorok.clear();

        if (chkTortenelmi.isSelected()) {
            temakorok.add(TemakorEnum.Tortenelmi);
            szamlalo++;
        }

        if (chkFoldrajzi.isSelected()) {
            temakorok.add(TemakorEnum.Foldrajzi);
            szamlalo++;
        }

        if (chkBulvar.isSelected()) {
            temakorok.add(TemakorEnum.Bulvar);
            szamlalo++;
        }

        if (chkElovilag.isSelected()) {
            temakorok.add(TemakorEnum.Elovilag);
            szamlalo++;
        }

        if (chkZene.isSelected()) {
            temakorok.add(TemakorEnum.Zene);
            szamlalo++;
        }

        if (chkFilmEsSzinhaz.isSelected()) {
            temakorok.add(TemakorEnum.FilmEsSzinhaz);
            szamlalo++;
        }

        if (chkKepzomuveszeti.isSelected()) {
            temakorok.add(TemakorEnum.Kepzomuveszeti);
            szamlalo++;
        }

        if (chkIrodalmi.isSelected()) {
            temakorok.add(TemakorEnum.Irodalmi);
            szamlalo++;
        }

        if (chkEtelekEsItalok.isSelected()) {
            temakorok.add(TemakorEnum.EtelekEsItalok);
            szamlalo++;
        }

        if (chkUnnepek.isSelected()) {
            temakorok.add(TemakorEnum.Unnepek);
            szamlalo++;
        }

        if (chkCsillagaszat.isSelected()) {
            temakorok.add(TemakorEnum.Csillagaszat);
            szamlalo++;
        }

        if (chkTvSorozat.isSelected()) {
            temakorok.add(TemakorEnum.TvSorozat);
            szamlalo++;
        }

        if (chkKozlekedesEsJarmuvek.isSelected()) {
            temakorok.add(TemakorEnum.KozlekedesEsJarmuvek);
            szamlalo++;
        }

        if (chkSzolasokEsKozmondasok.isSelected()) {
            temakorok.add(TemakorEnum.SzolasokEsKozmondasok);
            szamlalo++;
        }

        if (chkEgyeb.isSelected()) {
            temakorok.add(TemakorEnum.Egyeb);
            szamlalo++;
        }
        if (szamlalo - 1 == temakorok.size()) {
            return null;
        }

        return temakorok;

    }

    private void chkBoxokKipipalvaCsere() {
        chkTortenelmi.setSelected(osszesKerdesAktivalas);
        chkFoldrajzi.setSelected(osszesKerdesAktivalas);
        chkBulvar.setSelected(osszesKerdesAktivalas);
        chkElovilag.setSelected(osszesKerdesAktivalas);
        chkZene.setSelected(osszesKerdesAktivalas);
        chkFilmEsSzinhaz.setSelected(osszesKerdesAktivalas);
        chkKepzomuveszeti.setSelected(osszesKerdesAktivalas);
        chkIrodalmi.setSelected(osszesKerdesAktivalas);
        chkEtelekEsItalok.setSelected(osszesKerdesAktivalas);
        chkUnnepek.setSelected(osszesKerdesAktivalas);
        chkCsillagaszat.setSelected(osszesKerdesAktivalas);
        chkTvSorozat.setSelected(osszesKerdesAktivalas);
        chkKozlekedesEsJarmuvek.setSelected(osszesKerdesAktivalas);
        chkSzolasokEsKozmondasok.setSelected(osszesKerdesAktivalas);
        chkEgyeb.setSelected(osszesKerdesAktivalas);

    }

    public void bundleBeallitasPanel(boolean magyar, boolean angol) {
        btnMagyar.setEnabled(magyar);
        btnAngol.setEnabled(angol);
    }

    public void hangBEKI(boolean beVagyKi) {

        if (beVagyKi) {
            btnZene.setIcon(hangBe);
        } else {
            btnZene.setIcon(hangKi);
        }
    }

}
