/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import vezerles.Vezerlo;

/**
 *
 * @author Szintai
 */
public class MenuPanel extends javax.swing.JPanel {

    private Vezerlo vezerlo;
    ResourceBundle magyarBundle = ResourceBundle.getBundle("lokalitas/Bundle");
    ResourceBundle angolBundle = ResourceBundle.getBundle("lokalitas/Bundle_en");
    private Icon hangBe = new ImageIcon(getClass().getResource("/adatok/hangBe.png"));
    private Icon hangKi = new ImageIcon(getClass().getResource("/adatok/hangKi.png"));
    private Image hatterKep = new ImageIcon(getClass().getResource("/adatok/hatter4.jpg")).getImage();
    private String BEJELENTKEZES = "Bejelentkezés";
    private String JATEKVENDEGKENT = "Játék vendégként";
    private String MEGSE = "Mégse";
    private String NEVADASVAGYVENDEG = "Adjon meg nevet vagy játszon vendégként!";
    private String HOGYSZERETNEJATSZANI = "Hogy szeretne játszani?";
    private String JATEKLEIRAS = "Ez egy kvíz játék két fajta játékmóddal.\n\nA gyorsasági játékmódban két élete van a játékosnak. \nMinél gyorsabb a felhasználó, annál több pontot kap.\nEz a mód csak bejelentkezve érhető el. \n\nA másik mód az ügyességi mód. \nItt három élet adott és több idő a kérdés megválaszolására.";

    public MenuPanel() {
        initComponents();
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJatek = new javax.swing.JButton();
        btnBejelentkezes = new javax.swing.JButton();
        btnTemakorok = new javax.swing.JButton();
        btnSugo = new javax.swing.JButton();
        btnAngol = new javax.swing.JButton();
        btnMagyar = new javax.swing.JButton();
        btnZene = new javax.swing.JButton();

        btnJatek.setBackground(java.awt.SystemColor.activeCaption);
        btnJatek.setText("Játék");
        btnJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJatekActionPerformed(evt);
            }
        });

        btnBejelentkezes.setBackground(java.awt.SystemColor.activeCaption);
        btnBejelentkezes.setText("Bejelentkezés és Toplista");
        btnBejelentkezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBejelentkezesActionPerformed(evt);
            }
        });

        btnTemakorok.setBackground(java.awt.SystemColor.activeCaption);
        btnTemakorok.setText("Témakörök");
        btnTemakorok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemakorokActionPerformed(evt);
            }
        });

        btnSugo.setBackground(java.awt.SystemColor.activeCaption);
        btnSugo.setText("Súgó");
        btnSugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugoActionPerformed(evt);
            }
        });

        btnAngol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/eng.png"))); // NOI18N
        btnAngol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngolActionPerformed(evt);
            }
        });

        btnMagyar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/hun.png"))); // NOI18N
        btnMagyar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagyarActionPerformed(evt);
            }
        });

        btnZene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adatok/hangBe.png"))); // NOI18N
        btnZene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSugo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTemakorok, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJatek, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(btnMagyar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAngol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(196, 196, 196)
                                        .addComponent(btnZene, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(btnBejelentkezes)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnJatek, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSugo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBejelentkezes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAngol, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnMagyar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnZene)))
                .addGap(29, 29, 29)
                .addComponent(btnTemakorok, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJatekActionPerformed
        String[] buttons2 = {BEJELENTKEZES, JATEKVENDEGKENT, MEGSE};
        int rc2 = JOptionPane.showOptionDialog(null, NEVADASVAGYVENDEG, HOGYSZERETNEJATSZANI,
                JOptionPane.WARNING_MESSAGE, 0, null, buttons2, buttons2[0]);
        switch (rc2) {
            case 0:
                vezerlo.panelCsere(true, false, false, false);
                break;
            case 1:
                vezerlo.panelCsere(false, false, true, false);
                vezerlo.jatekInditas(1);
                break;
        }
    }//GEN-LAST:event_btnJatekActionPerformed

    private void btnBejelentkezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBejelentkezesActionPerformed

        vezerlo.panelCsere(true, false, false, false);

    }//GEN-LAST:event_btnBejelentkezesActionPerformed

    private void btnTemakorokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemakorokActionPerformed

        vezerlo.panelCsere(false, true, false, false);
    }//GEN-LAST:event_btnTemakorokActionPerformed

    private void btnSugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugoActionPerformed
        JOptionPane.showMessageDialog(null, JATEKLEIRAS);
    }//GEN-LAST:event_btnSugoActionPerformed

    private void btnAngolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngolActionPerformed
        vezerlo.nyelvvaltas(angolBundle);
        temakorMenuElerhetosegCsere(false);
        //  Jatekos.setAngolul(true);
        btnMagyar.setEnabled(true);
        btnAngol.setEnabled(false);
        vezerlo.bundleBeallitasPanel(true, false);
    }//GEN-LAST:event_btnAngolActionPerformed

    private void btnMagyarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagyarActionPerformed
        vezerlo.nyelvvaltas(magyarBundle);
        temakorMenuElerhetosegCsere(true);
        // Jatekos.setAngolul(false);
        btnMagyar.setEnabled(false);
        btnAngol.setEnabled(true);
        vezerlo.bundleBeallitasPanel(false, true);
    }//GEN-LAST:event_btnMagyarActionPerformed

    private void btnZeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeneActionPerformed
        if (!btnZene.getIcon().equals(hangKi)) {
            vezerlo.zeneBeKapcsolas();
            btnZene.setIcon(hangKi);
        vezerlo.beallitasPanelHangBEKI(false);
        } else {
            vezerlo.zeneKikapcsolas();
       vezerlo.beallitasPanelHangBEKI(true);
            btnZene.setIcon(hangBe);
        }
    }//GEN-LAST:event_btnZeneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAngol;
    private javax.swing.JButton btnBejelentkezes;
    private javax.swing.JButton btnJatek;
    private javax.swing.JButton btnMagyar;
    private javax.swing.JButton btnSugo;
    public javax.swing.JButton btnTemakorok;
    private javax.swing.JButton btnZene;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        g.drawImage(hatterKep, 0, 0, this.getWidth(), this.getHeight(), this);

    }

    public void nyelvBeallitas(ResourceBundle Bundle) {

        BEJELENTKEZES = Bundle.getString("MENU_BEJELENTKEZES");
        JATEKVENDEGKENT = Bundle.getString("MENU_JATEKVENDEGKENT");
        MEGSE = Bundle.getString("MENU_MEGSE");
        NEVADASVAGYVENDEG = Bundle.getString("MENU_NEVADASVAGYVENDEG");
        HOGYSZERETNEJATSZANI = Bundle.getString("MENU_HOGYSZERETNEJATSZANI");
        btnBejelentkezes.setText(Bundle.getString("BTN_BEALLITAS"));
        btnJatek.setText(Bundle.getString("BTN_JATEK"));
        btnSugo.setText(Bundle.getString("BTN_SUGO"));
        btnTemakorok.setText(Bundle.getString("BTN_TEMAKOROK"));
        JATEKLEIRAS = Bundle.getString("MENU_SUGOLEIRAS");
    }

    public JButton getBtnTemakorok() {
        return btnTemakorok;
    }

    public void temakorMenuElerhetosegCsere(boolean igazVagyHamis) {
        btnTemakorok.setEnabled(igazVagyHamis);

    }

    public void bundleMenuPanel(boolean magyar, boolean angol) {
        btnMagyar.setEnabled(magyar);
        btnAngol.setEnabled(angol);
    }

    public void hangBEKI(boolean beVagyKi) {
        if(beVagyKi)
        {btnZene.setIcon(hangBe);}
        else
        {btnZene.setIcon(hangKi);}
        
    }

}
